[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MATLAB = "10e44e05-a98a-55b3-a45b-ba969058deb6"
MBD = "994ce0ec-d6e5-428b-b4b3-7b10f5a0848a"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SPICE = "5bab7191-041a-5c2e-a744-024b9c3a5062"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UpdateJulia = "770da0de-323d-4d28-9202-0e205c1e0aff"
