[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MATLAB = "10e44e05-a98a-55b3-a45b-ba969058deb6"
MBD = "994ce0ec-d6e5-428b-b4b3-7b10f5a0848a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
UpdateJulia = "770da0de-323d-4d28-9202-0e205c1e0aff"
